const { sql, getPool } = require('../config/database');
const { dbMode } = require('../config/env');

const poolPromise = dbMode === 'memory' ? null : getPool();

const fields = 'id, first_name, last_name, email, contact_number, department, position, status, created_at, updated_at';
async function list({ search = '', status = '', department = '', page = 1, pageSize = 10 }) {
  const pool = await poolPromise; const offset = (Number(page) - 1) * Number(pageSize);
  const request = pool.request().input('search', sql.NVarChar, `%${search}%`).input('status', sql.NVarChar, status || null).input('department', sql.NVarChar, department || null).input('offset', sql.Int, offset).input('pageSize', sql.Int, Number(pageSize));
  const result = await request.query(`SELECT ${fields} FROM employees WHERE (first_name LIKE @search OR last_name LIKE @search OR email LIKE @search OR department LIKE @search) AND (@status IS NULL OR status = @status) AND (@department IS NULL OR department = @department) ORDER BY created_at DESC OFFSET @offset ROWS FETCH NEXT @pageSize ROWS ONLY; SELECT COUNT(*) AS total FROM employees WHERE (first_name LIKE @search OR last_name LIKE @search OR email LIKE @search OR department LIKE @search) AND (@status IS NULL OR status = @status) AND (@department IS NULL OR department = @department);`);
  return { records: result.recordsets[0], total: result.recordsets[1][0].total, page: Number(page), pageSize: Number(pageSize) };
}
async function getById(id) { const pool = await poolPromise; const result = await pool.request().input('id', sql.Int, id).query(`SELECT ${fields} FROM employees WHERE id = @id`); return result.recordset[0]; }
async function create(data) { const pool = await poolPromise; const result = await pool.request().input('first_name', sql.NVarChar, data.first_name).input('last_name', sql.NVarChar, data.last_name).input('email', sql.NVarChar, data.email).input('contact_number', sql.NVarChar, data.contact_number || null).input('department', sql.NVarChar, data.department).input('position', sql.NVarChar, data.position).input('status', sql.VarChar, data.status).query(`INSERT INTO employees (first_name,last_name,email,contact_number,department,position,status) OUTPUT INSERTED.${fields} VALUES (@first_name,@last_name,@email,@contact_number,@department,@position,@status)`); return result.recordset[0]; }
async function update(id, data) { const pool = await poolPromise; const result = await pool.request().input('id', sql.Int, id).input('first_name', sql.NVarChar, data.first_name).input('last_name', sql.NVarChar, data.last_name).input('email', sql.NVarChar, data.email).input('contact_number', sql.NVarChar, data.contact_number || null).input('department', sql.NVarChar, data.department).input('position', sql.NVarChar, data.position).input('status', sql.VarChar, data.status).query(`UPDATE employees SET first_name=@first_name,last_name=@last_name,email=@email,contact_number=@contact_number,department=@department,position=@position,status=@status,updated_at=SYSUTCDATETIME() OUTPUT INSERTED.${fields} WHERE id=@id`); return result.recordset[0]; }
async function remove(id) { const pool = await poolPromise; const result = await pool.request().input('id', sql.Int, id).query('DELETE FROM employees WHERE id=@id'); return result.rowsAffected[0] > 0; }
async function dashboard() { const pool = await poolPromise; const result = await pool.request().query("SELECT COUNT(*) AS total, SUM(CASE WHEN status='Active' THEN 1 ELSE 0 END) AS active, SUM(CASE WHEN status='Inactive' THEN 1 ELSE 0 END) AS inactive FROM employees; SELECT TOP 5 id, first_name, last_name, department, status, created_at FROM employees ORDER BY created_at DESC;"); return { stats: result.recordset[0], recent: result.recordsets[1] }; }
async function report(status) { const pool = await poolPromise; const request = pool.request().input('status', sql.VarChar, status || null); const result = await request.query(`SELECT ${fields} FROM employees WHERE (@status IS NULL OR status=@status) ORDER BY department, last_name; SELECT COUNT(*) AS total, SUM(CASE WHEN status='Active' THEN 1 ELSE 0 END) AS active, SUM(CASE WHEN status='Inactive' THEN 1 ELSE 0 END) AS inactive FROM employees WHERE (@status IS NULL OR status=@status);`); return { records: result.recordsets[0], summary: result.recordsets[1][0] }; }
module.exports = dbMode === 'memory' ? require('./memoryEmployeeService') : { list, getById, create, update, remove, dashboard, report };
